settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-sample
  path: .
  args:
  - cron.go
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
